### ISSUE TITLE
Set up the Optitrack Motion Capture System

### ISSUE THREAD

**Issue by moorepants** [mechmotum/housekeeping#11]
We need to setup the system and learn how it works.

The permanent setup probably cannot happen until the construction is finished about expanding the lab.

We can still learn the system before then.

**Comment by moorepants** [comment]
@Eimolgon can you an Jose update the status of this task here and make a todo list, otherwise maybe this all gets lost.

**Comment by Eimolgon** [comment]
## What has been done:
- [x] Inventory of the system
- [x] Set up software
- [x] Working space test
- [x] Connect Dell tower to internet (thanks to the faith!)

## To-Do:
- [x] Hang bars to mount cameras from the roof
- [x] Install bar between pillars (projector side)
- [ ] Close the recording space with curtains
- [x] Buy clamps for hanging bars
- [x] Tidy cables and connections
- [x] Definitive installation of hubs for connections

**Comment by Eimolgon** [comment]
We need to organize the use of the mocap as it requires the hardware key, and I think it can be a hassle to store it in the future locked cabinet in case that students want to use the mocap and nobody with the cabinet/drawer key is at uni.

**Comment by moorepants** [comment]
I think the cabinet key can be given to me, phd, postdocs, and lab coordinator. This should give sufficient opportunity for arranging use of specific things in the cabinet.

That hardware key may not need be locked up. It isn't valuable in and of itself.

**Comment by Eimolgon** [comment]
Then we can tie the hardware key to the computer so it doesn't get lost. Most of the time it should not be moved, but in case anyone needs to re arrange the usb ports, it will have its place.

**Comment by moorepants** [comment]
Do we need to put the hardware key in the new locked cabinet?
